services:
  api-example-server:
    image: axidex/api-example-server:latest
    ports:
      - "${API_PORT}:5000"
    volumes:
      - ./.env:/opt/api-example/.env:ro
    networks:
      - api-example

networks:
  api-example:
    external: true