services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otel-config.yaml"]
    networks:
      - api-example
    volumes:
      - ./otel-config.yaml:/etc/otel-config.yaml
    ports:
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP
      - "8889:8889"   # Prometheus metrics exposed by the collector
    depends_on:
      - prometheus
      - jaeger
      - loki

  prometheus:
    image: prom/prometheus:latest
    networks:
      - api-example
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  jaeger:
    image: jaegertracing/all-in-one:latest
    networks:
      - api-example
    ports:
      - "6831:6831/udp" # UDP port for Jaeger agent
      - "16686:16686" # Web UI
      - "14268:14268" # HTTP port for spans

  loki:
    image: grafana/loki:latest
    networks:
      - api-example
    command: ["-config.file=/etc/loki/local-config.yaml"]
    ports:
      - "5051:3100"

  grafana:
    image: grafana/grafana:latest
    networks:
      - api-example
    ports:
      - "5050:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - prometheus
      - jaeger
      - loki

volumes:
  grafana-storage:

networks:
  api-example:
    external: true