name: Build Go Service

on:
  workflow_call:
    inputs:
      service_dir:
        required: true
        type: string
      docker_image_name:
        required: true
        type: string

    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.service_dir }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git
        run: git fetch --tags

      - name: Lint Go code
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          working-directory: ${{ inputs.service_dir }}
          args: --timeout=5m

      - name: Compute build arguments
        id: build-vars
        run: |
          echo "BUILD_DATE=$(date -u +'%d.%m.%Y')" >> $GITHUB_OUTPUT
          echo "BUILD_COMMIT=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "latest")
          echo "BUILD_VERSION=$TAG" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: ./${{ inputs.service_dir }}
          file: ./${{ inputs.service_dir }}/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ inputs.docker_image_name }}:latest
            ${{ secrets.DOCKER_USERNAME }}/${{ inputs.docker_image_name }}:${{ steps.build-vars.outputs.BUILD_VERSION }}
          build-args: |
            BUILD_VERSION=${{ steps.build-vars.outputs.BUILD_VERSION }}
            BUILD_DATE=${{ steps.build-vars.outputs.BUILD_DATE }}
            BUILD_COMMIT=${{ steps.build-vars.outputs.BUILD_COMMIT }}
