name: Build Go Service Docker Image (Reusable)

on:
  workflow_call:
    inputs:
      service_dir:
        required: true
        type: string
        description: 'Service directory name (server/transactions)'
      docker_image_name:
        required: true
        type: string
        description: 'Docker image name (api-example-server/api-example-transactions)'

    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ inputs.service_dir }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compute build arguments
        id: build-vars
        run: |
          echo "BUILD_DATE=$(date -u +'%d.%m.%Y')" >> $GITHUB_OUTPUT
          echo "BUILD_COMMIT=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          
          if [[ "$GITHUB_REF_TYPE" == "tag" ]]; then
            echo "BUILD_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          else
            BRANCH_NAME="${GITHUB_REF#refs/heads/}"
            SAFE_BRANCH_NAME=$(echo "$BRANCH_NAME" | sed 's/[^a-zA-Z0-9_.-]/-/g')
            echo "BUILD_VERSION=$SAFE_BRANCH_NAME" >> $GITHUB_OUTPUT
          fi

      - name: Version
        run: echo "${{ steps.build-vars.outputs.BUILD_VERSION }}${{ steps.build-vars.outputs.BUILD_DATE }} ${{ steps.build-vars.outputs.BUILD_COMMIT }}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./${{ inputs.service_dir }}
          file: ./${{ inputs.service_dir }}/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ inputs.docker_image_name }}:${{ steps.build-vars.outputs.BUILD_VERSION }}
          build-args: |
            BUILD_VERSION=${{ steps.build-vars.outputs.BUILD_VERSION }}
            BUILD_DATE=${{ steps.build-vars.outputs.BUILD_DATE }}
            BUILD_COMMIT=${{ steps.build-vars.outputs.BUILD_COMMIT }}
