name: Build Server Branch

on:
  push:
    branches: ['release/**']
  workflow_dispatch:

jobs:
  call-ci:
    uses: ./.github/workflows/go-ci.yml
    with:
      service_dir: 'server'

  build:
    needs: [ call-ci ]
    uses: ./.github/workflows/docker-build-release.yml
    with:
      service_dir: 'server'
      docker_image_name: 'api-example-server'
      create_tag: true
      tag_prefix: 'v'
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
