name: Build Go Server Docker Image Branch

on:
  push:
    branches:
      - 'feature/**'
    tags:
      - '*'

  pull_request:
    branches:
      - main
      - 'feature/**'

jobs:
  call-ci:
    uses: ./.github/workflows/go-ci.yml
  call-sec:
    uses: ./.github/workflows/go-sec.yml

  build-server:
    runs-on: ubuntu-latest
    needs:
      - call-ci
    defaults:
      run:
        working-directory: server

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compute build arguments
        id: build-vars
        run: |
          echo "BUILD_DATE=$(date -u +'%d.%m.%Y')" >> $GITHUB_OUTPUT
          echo "BUILD_COMMIT=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          SAFE_BRANCH_NAME=$(echo "$BRANCH_NAME" | tr '/' '-' | tr -cd '[:alnum:]._-')
          echo "BUILD_VERSION=$SAFE_BRANCH_NAME" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./server
          file: ./server/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/api-example-server:${{ steps.build-vars.outputs.BUILD_VERSION }}
          build-args: |
            BUILD_VERSION=${{ steps.build-vars.outputs.BUILD_VERSION }}
            BUILD_DATE=${{ steps.build-vars.outputs.BUILD_DATE }}
            BUILD_COMMIT=${{ steps.build-vars.outputs.BUILD_COMMIT }}
